version: "3.3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: apidados_user
      POSTGRES_PASSWORD: apidados_password
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
