micronaut:
  application:
    name: datapublisher
api-flask:
  url:  https://8023-35-245-12-26.ngrok.io/resumo
netty:
  default:
    allocator:
      max-order: 3
endpoints:
  liquibase:
    enabled: true
    sensitive: false