micronaut:
  application:
    name: datapublisher
    server:
      cors: true
      max-request-size: 10GB
      multipart:
        max-file-size: XXXMB
        mixed: true
        disk: true
        location: /tmp

api-flask:
  url:  http://057a-34-125-230-13.ngrok.io/

jackson:
  bean-introspection-module: true

netty:
  default:
    allocator:
      max-order: 3

endpoints:
  liquibase:
    enabled: true
    sensitive: false

vertx:
  pg:
    client:
      port: 5432
      host: localhost
      database: api_dados_database_local
      user: apidados_user
      password: apidados_password
      maxSize: 5
micronaut.codec.json.additionalTypes: ["text/html"]